version: "3.9"

services:
  redis:
    restart: always
    image: "redis:latest"
    container_name: "redis-server"
    command: redis-server --requirepass <PASSWORD>
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
